feature: pictureInpicture
BICBT/cloudswitcher-server pull request #57
Opened 2021-09-26 09:47 UTC by lisr2016

2021-09-29 17:02 UTC, MengLi619 requested changes

2021-09-29 17:02 UTC, MengLi619 commented on src/component/types.ts
> +import {IsArray, IsBoolean, IsEnum, IsNotEmpty, IsNumber, IsOptional, IsString, ValidateNested} from 'class-validator';
Keep code format consistancy.

2021-09-29 17:02 UTC, MengLi619 commented on src/component/types.ts
> +    id:string;
Code format

2021-09-29 17:02 UTC, MengLi619 commented on src/component/types.ts
> +  pipIndex?: number;
Where do we use these two properties?

2021-09-30 03:34 UTC, lisr2016 commented on src/component/obs.ts
> -  obs.removeScene(sourceId);
mistaken

2021-09-30 03:37 UTC, lisr2016 commented on src/controller/pictureinpicturecontroller.ts
> +    deleteSource(pictureInPictureId);
corrected

2021-09-30 04:03 UTC, lisr2016 commented on src/component/types.ts
> +}
x,y,width,height 是为后面的自定义画中画准备的

2021-09-30 05:33 UTC, closed without merging